# This workflow is to test Github secrets
name: Test github secrets
on:
  workflow_dispatch:
    inputs:
      env-name:
        description: Name of the environment to deploy to
        type: string
        required: true
        default: dev
  push:
    branches:
      - test-github-secrets



jobs:
  job1:
    name: 'test Github secret'
    runs-on: ubuntu-latest
    environment: dev
    permissions:
      id-token: write
      contents: read
    steps:
      - name: test github secrets
        run: |
          api_key_json=${{ secrets.TEST }}
          echo "Extracted API Key JSON: $api_key_json"
    
